// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Chain, ChainData, ChainTableId } from "./tables/Chain.sol";
import { Land, LandTableId } from "./tables/Land.sol";
import { OffchainLand, OffchainLandTableId } from "./tables/OffchainLand.sol";
import { Pixel, PixelData, PixelTableId } from "./tables/Pixel.sol";
import { AddressInfo, AddressInfoData, AddressInfoTableId } from "./tables/AddressInfo.sol";
import { AddressBoard, AddressBoardTableId } from "./tables/AddressBoard.sol";
