// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAddressEntitySystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAddressEntitySystem {
  function setAddressInfo(address contract_address, string memory name, string memory description) external;

  function changeAddressName(address contract_address, string memory name) external;

  function changeAddressDescription(address contract_address, string memory description) external;
}
