// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILandEntitySystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILandEntitySystem {
  function emitReserveLandEntity(uint16 chain_id, uint8 land_id, uint8 pixel_id) external;

  function emitReleaseLandEntity(uint16 chain_id, uint8 land_id) external;
}
